const SlidersActionsTypes = {
    FETCH_SLIDERS_START : 'FETCH_SLIDERS_START',
    FETCH_SLIDERS_SUCCESS : 'FETCH_SLIDERS_SUCCESS',
    FETCH_SLIDERS_FAILURE : 'FETCH_SLIDERS_FAILURE',
};

export default SlidersActionsTypes;
