const DesignActionTypes = {
    SET_CURRENT_PAGE_NAV: 'SET_CURRENT_PAGE_NAV',
    SET_CURRENT_SECTION: 'SET_CURRENT_SECTION',
    TOGGLE_SHOP_SIDEBAR: 'TOGGLE_SHOP_SIDEBAR',
    TOGGLE_SEARCH_HIDDEN: 'TOGGLE_SEARCH_HIDDEN',
};

export default DesignActionTypes;
